[project]
name = "streamlit-app-deployment-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit",
    "pandas",
    "numpy",
    "plotly"
]

[tool.streamlit]
package-mode = false
